# Generated by Django 5.2.13 on 2026-04-27 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("boolean", "Boolean"),
                            ("variant", "Variant"),
                        ],
                        default="boolean",
                        max_length=16,
                    ),
                ),
                ("default_value", models.CharField(max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("sticky_assignment", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="FeatureRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("priority", models.PositiveIntegerField(default=100)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("authenticated", "Authenticated"),
                            ("staff", "Staff"),
                            ("user_allowlist", "User allowlist"),
                            ("user_denylist", "User denylist"),
                            ("anonymous_allowlist", "Anonymous allowlist"),
                            ("anonymous_denylist", "Anonymous denylist"),
                            ("percentage", "Percentage rollout"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(max_length=64)),
                (
                    "page",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("actor_ids", models.JSONField(blank=True, default=list)),
                (
                    "percentage",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="featureflags.featuredefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExperimentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("user", "User"), ("anonymous", "Anonymous")],
                        max_length=16,
                    ),
                ),
                ("subject_key", models.CharField(max_length=128)),
                (
                    "page",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("value", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="featureflags.featuredefinition",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "feature__key",
                    "subject_type",
                    "subject_key",
                    "page",
                ],
                "unique_together": {
                    ("feature", "subject_type", "subject_key", "page")
                },
            },
        ),
        migrations.CreateModel(
            name="FeatureOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("user", "User"),
                            ("anonymous", "Anonymous"),
                        ],
                        default="global",
                        max_length=16,
                    ),
                ),
                (
                    "scope_value",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("value", models.CharField(max_length=64)),
                ("note", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feature_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="featureflags.featuredefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["feature__key", "scope_type", "scope_value"],
                "unique_together": {("feature", "scope_type", "scope_value")},
            },
        ),
    ]
