# Generated by Django 5.2.13 on 2026-05-08 00:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureflags', '0002_seed_homepage_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerule',
            name='group_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of FeatureGroup IDs for GROUP rule type.'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='rule_type',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('authenticated', 'Authenticated'), ('staff', 'Staff'), ('group', 'Group membership'), ('user_allowlist', 'User allowlist'), ('user_denylist', 'User denylist'), ('anonymous_allowlist', 'Anonymous allowlist'), ('anonymous_denylist', 'Anonymous denylist'), ('percentage', 'Percentage rollout')], max_length=32),
        ),
        migrations.CreateModel(
            name='FeatureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='feature_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFeatureDefinition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('boolean', 'Boolean'), ('variant', 'Variant')], default='boolean', max_length=16)),
                ('default_value', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('sticky_assignment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical feature definition',
                'verbose_name_plural': 'historical feature definitions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFeatureOverride',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('user', 'User'), ('anonymous', 'Anonymous')], default='global', max_length=16)),
                ('scope_value', models.CharField(blank=True, default='', max_length=128)),
                ('value', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='featureflags.featuredefinition')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical feature override',
                'verbose_name_plural': 'historical feature overrides',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFeatureRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('rule_type', models.CharField(choices=[('everyone', 'Everyone'), ('authenticated', 'Authenticated'), ('staff', 'Staff'), ('group', 'Group membership'), ('user_allowlist', 'User allowlist'), ('user_denylist', 'User denylist'), ('anonymous_allowlist', 'Anonymous allowlist'), ('anonymous_denylist', 'Anonymous denylist'), ('percentage', 'Percentage rollout')], max_length=32)),
                ('value', models.CharField(max_length=64)),
                ('page', models.CharField(blank=True, default='', max_length=64)),
                ('actor_ids', models.JSONField(blank=True, default=list)),
                ('group_ids', models.JSONField(blank=True, default=list, help_text='List of FeatureGroup IDs for GROUP rule type.')),
                ('percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('feature', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='featureflags.featuredefinition')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical feature rule',
                'verbose_name_plural': 'historical feature rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
