# Generated by Django 5.2.5 on 2026-02-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    UserProfile = apps.get_model("core", "UserProfile")
    existing_user_ids = set(
        UserProfile.objects.values_list("user_id", flat=True)
    )
    to_create = [
        UserProfile(user_id=user_id)
        for user_id in User.objects.values_list("id", flat=True)
        if user_id not in existing_user_ids
    ]
    if to_create:
        UserProfile.objects.bulk_create(to_create, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vk_username",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "minecraft_nick",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "minecraft_has_license",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "is_itmo_student",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "itmo_isu",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extended_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "updated_at"],
                        name="core_userpr_user_id_557362_idx",
                    ),
                    models.Index(
                        fields=["is_itmo_student"],
                        name="core_userpr_is_itmo_17f9c2_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            create_profiles_for_existing_users,
            migrations.RunPython.noop,
        ),
    ]
