# Generated by Django 5.2.5 on 2026-03-10 22:45

import re

from django.conf import settings
from django.db import migrations


MINECRAFT_NICK_RE = re.compile(r"^[A-Za-z0-9_]{3,16}$")


def backfill_legacy_minecraft_nicks(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    UserProfile = apps.get_model("core", "UserProfile")

    existing_user_ids = set(
        UserProfile.objects.values_list("user_id", flat=True)
    )
    missing_profiles = [
        UserProfile(user_id=user_id)
        for user_id in User.objects.values_list("id", flat=True)
        if user_id not in existing_user_ids
    ]
    if missing_profiles:
        UserProfile.objects.bulk_create(missing_profiles, ignore_conflicts=True)

    for profile in UserProfile.objects.select_related("user").iterator():
        if (profile.minecraft_nick or "").strip():
            continue
        username = (getattr(profile.user, "username", "") or "").strip()
        if not MINECRAFT_NICK_RE.fullmatch(username):
            continue
        profile.minecraft_nick = username
        profile.save(update_fields=["minecraft_nick", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            backfill_legacy_minecraft_nicks,
            migrations.RunPython.noop,
        ),
    ]
