# Generated by Django 5.2.13 on 2026-04-26 19:19

from django.conf import settings
from django.db import migrations, models
from django.utils.crypto import salted_hmac

SESSION_TOKEN_DIGEST_SALT = "core.UserSessionMeta.session_token.v1"


def _session_token_digest(value):
    raw = (value or "").strip()
    if not raw:
        return ""
    return salted_hmac(SESSION_TOKEN_DIGEST_SALT, raw).hexdigest()


def backfill_session_token_digest(apps, _schema_editor):
    UserSessionMeta = apps.get_model("core", "UserSessionMeta")
    rows = (
        UserSessionMeta.objects.exclude(session_token__isnull=True)
        .exclude(session_token="")
        .iterator()
    )
    for meta in rows:
        meta.session_token_digest = _session_token_digest(meta.session_token)
        meta.session_token = None
        meta.save(update_fields=["session_token_digest", "session_token"])


def noop_reverse(_apps, _schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_backfill_legacy_minecraft_nicks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="usersessionmeta",
            name="core_userse_user_id_b1d5f0_idx",
        ),
        migrations.AddField(
            model_name="usersessionmeta",
            name="session_token_digest",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True
            ),
        ),
        migrations.RunPython(
            backfill_session_token_digest,
            reverse_code=noop_reverse,
        ),
        migrations.AlterField(
            model_name="usersessionmeta",
            name="session_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="usersessionmeta",
            index=models.Index(
                fields=["user", "session_token_digest"],
                name="core_userse_user_id_eedaf7_idx",
            ),
        ),
    ]
